#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"syscall_gen/syscall_num.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}


# oscomp: xv6 user codes can also use these syscall
entry("openat");
entry("execve");
entry("getdents");
entry("chdir");
entry("getcwd");

# xv6
entry("fork");
entry("exit");
entry("wait");      
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
